name: CI Pipeline

on:
  push:
    branches:
      - "**"

jobs:
  ci:
    name: Docker Build and Push to GHCR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to GHCR
        run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Build Docker image
        run: |
          IMAGE=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker build -t ${IMAGE}:${{ github.sha }} .
          docker tag ${IMAGE}:${{ github.sha }} ${IMAGE}:latest

      - name: Run container and health check
        run: |
          IMAGE=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker run -d -p 3000:3000 --name nodecontainer ${IMAGE}:${{ github.sha }}
          sleep 5
          curl http://localhost:3000/health

      - name: Push to GHCR
        if: github.ref == 'refs/heads/main'
        run: |
          IMAGE=ghcr.io/$(echo "${{ github.repository }}" | tr '[:upper:]' '[:lower:]')
          docker push ${IMAGE}:${{ github.sha }}
          docker push ${IMAGE}:latest